// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fogvmpkgzaqpjycrrrbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvZ3ZtcGtnemFxcGp5Y3JycmJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTIzNTUsImV4cCI6MjA2OTU4ODM1NX0.qSqt8yUgOv9A9rRaxFfEu1b7fXAhByXWDr8F4hNoVHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});